### ISSUE TITLE
problem testing e2e in docker image

### ISSUE THREAD

**Issue by geoHeil** [lathonez/clicker#114]
Hi, I have problems running the e2e tests in the following docker image: https://gist.github.com/geoHeil/48cd94bf4d748fd8fd6d25de4c272157

Chrome seems to be unreachable, even though chromium is installed:
```
WebDriverError: chrome not reachable
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.4.14-moby x86_64)
    at WebDriverError (/home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at Object.checkLegacyResponse (/home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/error.js:580:13)
    at /home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:64:13
    at Promise.invokeCallback_ (/home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at /home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
    at /home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:369:9)
From: Task: WebDriver.createSession()
    at acquireSession (/home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
    at Function.createSession (/home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
    at Driver (/home/jenkins/clicker/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/home/jenkins/clicker/node_modules/protractor/built/driverProviders/direct.js:65:26)
    at Runner.createBrowser (/home/jenkins/clicker/node_modules/protractor/built/runner.js:182:43)
    at /home/jenkins/clicker/node_modules/protractor/built/runner.js:255:30
    at _fulfilled (/home/jenkins/clicker/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/jenkins/clicker/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/jenkins/clicker/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/jenkins/clicker/node_modules/protractor/node_modules/q/q.js:556:49
```

**Comment by geoHeil** [comment]
I updated the Dockerfile to use chrome https://gist.github.com/geoHeil/48cd94bf4d748fd8fd6d25de4c272157 but still keep getting this error.

**Comment by lathonez** [comment]
I can't build using that dockerfile, which is relies on files that exist on your system.

In particular I'm getting:

```
Step 10 : COPY /files/authorized_keys /home/jenkins/.ssh/authorized_keys
lstat files/authorized_keys: no such file or directory
```

But I can see plenty of steps later on in the file that should also fail.

Have you looked at our [travis.yml](https://github.com/lathonez/clicker/blob/master/.travis.yml)?

**Comment by geoHeil** [comment]
Which steps are you referring to? They all do work. For the keys, you can use any random key.

Currently, I try to use https://github.com/jciolek/docker-protractor-headless respectively http://tobyho.com/2015/01/09/headless-browser-testing-xvfb/

**Comment by lathonez** [comment]
Sorry if I was unclear.

I ran `docker build -t clicker_114 .` in an empty directory containing [your dockerfile](https://gist.github.com/geoHeil/48cd94bf4d748fd8fd6d25de4c272157)

and got the following error:

```
Step 10 : COPY /files/authorized_keys /home/jenkins/.ssh/authorized_keys
lstat files/authorized_keys: no such file or directory
```

I presume any steps referencing `/files` would fail:

```
x220:~/code/clicker_114$ grep files Dockerfile 
COPY /files/authorized_keys /home/jenkins/.ssh/authorized_keys
COPY /files/resolv.conf /etc/resolv.conf
COPY /files/installAndroid.sh /installAndroid.sh
```

Could you provide command(s) I can run to generate the docker image you refer to, or (preferably) make an image available that I can pull down.

> Currently, I try to use https://github.com/jciolek/docker-protractor-headless respectively http://tobyho.com/2015/01/09/headless-browser-testing-xvfb/

I am unclear whether this means you have solved your problem or not?

**Comment by geoHeil** [comment]
The problem is not solved yet. I will update the dockerfile for you late afternoon. Thanks a lot for the support.

**Comment by geoHeil** [comment]
I updated the dockerfile here: https://gist.github.com/geoHeil/48cd94bf4d748fd8fd6d25de4c272157 
a npm test should run just fine,
a npm run e2e should unfortunately fail.

**Comment by lathonez** [comment]
Everything is owned by root so I can't run any tests:

```
jenkins@1bdea5fd764a:~/clicker$ ls -ltr
total 60
drwxr-xr-x  3 root root    38 Jul  5 08:19 www
-rw-r--r--  1 root root   403 Jul  5 08:19 typings.json
-rw-r--r--  1 root root  2550 Jul  5 08:19 tslint.json
-rw-r--r--  1 root root   321 Jul  5 08:19 tsconfig.json
drwxr-xr-x  3 root root   150 Jul  5 08:19 test
drwxr-xr-x  4 root root    66 Jul  5 08:19 resources
-rw-r--r--  1 root root  2418 Jul  5 08:19 package.json
-rw-r--r--  1 root root    48 Jul  5 08:19 ionic.project
-rw-r--r--  1 root root    76 Jul  5 08:19 ionic.config.json
drwxr-xr-x  3 root root    44 Jul  5 08:19 hooks
-rw-r--r--  1 root root  2264 Jul  5 08:19 gulpfile.js
-rw-r--r--  1 root root  1319 Jul  5 08:19 config.xml
drwxr-xr-x  7 root root   147 Jul  5 08:19 app
-rw-r--r--  1 root root  3968 Jul  5 08:19 README.md
-rw-r--r--  1 root root  1078 Jul  5 08:19 LICENSE
-rw-r--r--  1 root root 13345 Jul  5 08:19 CHANGELOG.md
drwxr-xr-x 44 root root  4096 Jul  5 08:20 node_modules
drwxr-xr-x  3 root root    39 Jul  5 08:23 typings
jenkins@1bdea5fd764a:~/clicker$ 
```

```
jenkins@1bdea5fd764a:~/clicker$ npm test

> clicker@1.8.1 test /home/jenkins/clicker
> gulp --gulpfile test/gulpfile.ts --cwd ./ unit-test

[08:39:39] Requiring external module ts-node/register
[08:39:42] Using gulpfile ~/clicker/test/gulpfile.ts
[08:39:42] Starting 'unit-test'...
[08:39:42] Starting 'lint'...
[08:39:42] Starting 'html'...
[08:39:42] 'html' errored after 228 ms
[08:39:42] Error: EACCES: permission denied, mkdir '/home/jenkins/clicker/www/build'
    at Error (native)
[08:39:42] 'unit-test' errored after 385 ms
[08:39:42] Error in plugin 'run-sequence(html)'
Message:
    html stream
[08:39:43] Finished 'lint' after 1.37 s
npm ERR! Test failed.  See above for more details.
```

what's the sudo password for jenkins / how can I connect as root?

**Comment by geoHeil** [comment]
A bad quick- fix is to just remove the last `USER jenkins` statement.
A cleaner fix is to re-checkout the repository into `/home/jenkins` with the default `jenkins` user

**Comment by geoHeil** [comment]
I updated the dockerfile.
Chrome does not seem to be available. However directly starting chrome results in this strange error: `xvfb-run google-chrome google.com`
![1__jenkins_68dd4423752e___var__docker_](https://cloud.githubusercontent.com/assets/1694964/16582031/c031a708-42ac-11e6-85ab-c901af209d47.jpg)

**Comment by lathonez** [comment]
> A cleaner fix is to re-checkout the repository into /home/jenkins with the default jenkins user

Sorry, should have figured that one out. Lots going on. I'm with you now.

Yeah I figure it's something to do with the xdisplay.

Travis is headless and we do 

```
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start
```

before the tests (why I was referencing it before)

**Comment by lathonez** [comment]
@geoHeil how can I get root in this image?

**Comment by geoHeil** [comment]
You can change the User int he dockerfile via `USER root` and then re-build the image. 
In casue you just add it at the bottom this will be very quick due to dockers cache.

**Comment by lathonez** [comment]
Finally got it working, though not in your image at the moment.

I'm running arch which has a ton of problems with google chrome on the standard kernel: ref https://github.com/jfrazelle/dockerfiles/issues/65 and has caused me no end of issues.

I'm hoping the key is:

`"e2e": "gulp --gulpfile test/gulpfile.ts --cwd ./ build-e2e && xvfb-run protractor test/protractor.conf.js"`

in package.json

**Comment by lathonez** [comment]
I'm not sure how much of a problem that is. Chrome stayed up for me.

dbus seems pretty badly broken on your image.

On my image I solved the error you mention by:

```
apt-get install dbus-x11
service dbus start
```

before running chrome.. tbh I don't think it's causing a problem

**Comment by lathonez** [comment]
It works, modify your package.json:

```
jenkins@f007b5e7eec4:~/clicker$ git diff package.json 
diff --git a/package.json b/package.json
index 67f354a..065e5b0 100644
--- a/package.json
+++ b/package.json
@@ -61,7 +61,7 @@
   "cordovaPlatforms": [],
   "scripts": {
     "build": "gulp --gulpfile test/gulpfile.ts --cwd ./ build-app",
-    "e2e": "gulp --gulpfile test/gulpfile.ts --cwd ./ build-e2e && protractor test/protractor.c
+    "e2e": "gulp --gulpfile test/gulpfile.ts --cwd ./ build-e2e && xvfb-run protractor test/pro
     "karma": "gulp --gulpfile test/gulpfile.ts --cwd ./ karma-debug",
     "postinstall": "ionic state restore && typings install && webdriver-manager update && cp te
     "start": "ionic serve",
```

**Comment by geoHeil** [comment]
Wow thanks a lot. But still I do not quite get it working:
after a 
`./node_modules/protractor/bin/webdriver-manager update` because only the global driver was updated
I get the well known timeout that chrome is unreachable:
```
Finished 'clean-test' after 13 ms
[14:21:12] Starting 'build-e2e'...
[14:21:14] Finished 'build-e2e' after 1.72 s
[14:21:14] I/direct - Using ChromeDriver directly...
[14:21:14] I/launcher - Running 1 instances of WebDriver

/home/clicker/node_modules/protractor/node_modules/selenium-webdriver/error.js:27
    super(opt_error);
         ^
WebDriverError: chrome not reachable
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.4.14-moby x86_64)
    at WebDriverError (/home/clicker/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at Object.checkLegacyResponse (/home/clicker/node_modules/protractor/node_modules/selenium-webdriver/error.js:580:13)
    at /home/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:64:13
    at Promise.invokeCallback_ (/home/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/home/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/home/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at /home/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
    at /home/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:369:9)
From: Task: WebDriver.createSession()
    at acquireSession (/home/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
    at Function.createSession (/home/clicker/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
    at Driver (/home/clicker/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/home/clicker/node_modules/protractor/built/driverProviders/direct.js:65:26)
    at Runner.createBrowser (/home/clicker/node_modules/protractor/built/runner.js:182:43)
    at /home/clicker/node_modules/protractor/built/runner.js:255:30
    at _fulfilled (/home/clicker/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/clicker/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/clicker/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/clicker/node_modules/protractor/node_modules/q/q.js:556:49
[14:22:14] E/launcher - Process exited with error code 1
```

**Comment by lathonez** [comment]
There's no need to update the webdriver it's done on install.

If you make that change to package.json it should work fine, as it does
here on the image you supplied.

I can send your image back to you tomorrow if it'll help you figure things
out.

**Comment by geoHeil** [comment]
Thanks a lot finally I got it working - well sort of:
![1__docker](https://cloud.githubusercontent.com/assets/1694964/16590195/d390ef0a-42d6-11e6-81a7-88a75e617c78.jpg)

**Comment by lathonez** [comment]
I've added a little info and a reference to this issue on the e2e blog.

https://github.com/lathonez/lathonez.github.io/commit/2275acf93832048566657a0baa4e3aa635f25f4d
