### ISSUE TITLE
Error trying to run npm test. no angular-cli-build.js

### ISSUE THREAD

**Issue by qngODC** [lathonez/clicker#153]
No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.

```
Error: No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/opt/development/projects/tyde/medicine/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:57:13)
    at Class.module.exports.Task.extend.init (/opt/development/projects/tyde/medicine/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/opt/development/projects/tyde/medicine/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/opt/development/projects/tyde/medicine/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at win.checkWindowsElevation.then (/opt/development/projects/tyde/medicine/node_modules/angular-cli/addon/ng2/commands/test.js:63:30)
    at tryCatch (/opt/development/projects/tyde/medicine/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/opt/development/projects/tyde/medicine/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at /opt/development/projects/tyde/medicine/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:628:16
    at flush (/opt/development/projects/tyde/medicine/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
 v6.4.0 (npm v3.10.3)
```

  "dependencies": {
    "@ionic/storage": "^1.0.3",
    "@types/lodash": "^4.14.36",
    "@types/node": "^6.0.42",
    "ionic-angular": "^2.0.0-rc.0",
    "ionic-native": "^2.0.3",
    "ionicons": "^3.0.0",
    "lodash": "^4.16.3",
    "moment": "^2.15.1"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.30",
    "angular-cli": "^0.1.0",
    "codelyzer": "0.0.28",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "^2.7.0",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.2.0",
    "karma-remap-istanbul": "^0.2.1",
    "tslint": "^3.15.1",
    "typescript": "^2.0.3"
  },

**Comment by lathonez** [comment]
Please provide a repro against clicker or some other repository I can test
with.

**Comment by lathonez** [comment]
Reopen if necessary (as above)
