### ISSUE TITLE
No Provider for DeepLinker!

### ISSUE THREAD

**Issue by jorgeitenjr** [lathonez/clicker#216]
Hi, I am just trying to add a component (TopTabPage) in my page and expecting my instance to be truthy. Have someone got the same problem or/and know the solution?
```
FAILED TESTS:
  HomePage
    ✖ initialises
      Chrome 55.0.2883 (Mac OS X 10.11.6)
    Error: No provider for DeepLinker!
        at NoProviderError.BaseError [as constructor] (webpack:///~/@angular/core/src/facade/errors.js:24:0 <- src/test.ts:7948:34)
        at NoProviderError.AbstractProviderError [as constructor] (webpack:///~/@angular/core/src/di/reflective_errors.js:41:0 <- src/test.ts:52518:16)
        at new NoProviderError (webpack:///~/@angular/core/src/di/reflective_errors.js:72:0 <- src/test.ts:52549:16)
        at ReflectiveInjector_._throwOrNull (webpack:///~/@angular/core/src/di/reflective_injector.js:758:0 <- src/test.ts:97335:19)
        at ReflectiveInjector_._getByKeyDefault (webpack:///~/@angular/core/src/di/reflective_injector.js:786:0 <- src/test.ts:97363:25)
        at ReflectiveInjector_._getByKey (webpack:///~/@angular/core/src/di/reflective_injector.js:749:0 <- src/test.ts:97326:25)
        at ReflectiveInjector_.get (webpack:///~/@angular/core/src/di/reflective_injector.js:558:0 <- src/test.ts:97135:21)
        at TestBed.get (webpack:///~/@angular/core/bundles/core-testing.umd.js:814:0 <- src/test.ts:12226:67)
        at CompiledTemplate.proxyViewClass.AppView.injectorGet (webpack:///~/@angular/core/src/linker/view.js:109:0 <- src/test.ts:97877:45)
        at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (webpack:///~/@angular/core/src/linker/view.js:351:0 <- src/test.ts:98119:49)
    Error: Uncaught (in promise): Error: Error in ./TopTabPage class TopTabPage - inline template:0:0 caused by: No provider for DeepLinker!
        at resolvePromise (webpack:///~/zone.js/dist/zone.js:468:0 <- src/test.ts:118950:31)
        at resolvePromise (webpack:///~/zone.js/dist/zone.js:453:0 <- src/test.ts:118935:17)
        at webpack:///~/zone.js/dist/zone.js:502:0 <- src/test.ts:118984:17
        at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:265:0 <- src/test.ts:118747:35)
        at ProxyZoneSpec.onInvokeTask (webpack:///~/zone.js/dist/proxy.js:103:0 <- src/test.ts:88858:39)
        at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:264:0 <- src/test.ts:118746:40)
        at Zone.runTask (webpack:///~/zone.js/dist/zone.js:154:0 <- src/test.ts:118636:47)
        at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:401:0 <- src/test.ts:118883:35)
        at ZoneTask.invoke (webpack:///~/zone.js/dist/zone.js:339:0 <- src/test.ts:118821:25)
        at data.args.(anonymous function) (webpack:///~/zone.js/dist/zone.js:970:0 <- src/test.ts:119452:25)
```

**Comment by lathonez** [comment]
There's no provider for DeepLinker.

Try adding it to the providers in test.ts.

**Comment by jorgeitenjr** [comment]
I tried, then I got: ` Can't resolve all parameters for DeepLinker: (?, ?, ?).`
The parameters are: (_app: App, _serializer: UrlSerializer, _location: Location);
Is there a way to inform the provider's parameter?
I also tried to create a mock to it but then: caused by:` this.parent.registerChildNav is not a function`

**Comment by lathonez** [comment]
Mocking was probably the way to go. From the limited details provided it looks like "DeepLinker" expects a parent variable with of type NavController (NavMock). I've not heard of DeepLinker and am AFK so can't be sure. 

As there is no issue with the repository I am going to close this issue, please see #191 for the suggested path for getting help with general unit testing problems. 

Thanks

**Comment by kamok** [comment]
@jorgeitenjr You got that mock written? I'm running into this now that I've upgraded to Ionic 3

**Comment by lathonez** [comment]
Had this issue with a component using `ion-select`, the following worked:

```
        {provide: DeepLinker, useFactory: () => ConfigMock.instance()},
```

basically mock out the deep linker with something. MMV with tabs page

**Comment by santoshnayak1996** [comment]
> Had this issue with a component using `ion-select`, the following worked:
> 
> ```
>         {provide: DeepLinker, useFactory: () => ConfigMock.instance()},
> ```
> 
> basically mock out the deep linker with something. MMV with tabs page

yay it's working
