### ISSUE TITLE
Error run npm test

### ISSUE THREAD

**Issue by marcelofb** [lathonez/clicker#223]
Hi, i have this error when run 'npm test':

/home/marcelo/clicker/node_modules/@ngtools/json-schema/src/schema-class-factory.js:47
    constructor(schema, value, ...fallbacks) {
                               ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/marcelo/AlquileresIonic2/node_modules/@ngtools/json-schema/src/index.js:2:30)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
npm ERR! Test failed.  See above for more details.

Any solution??

**Comment by lathonez** [comment]
Closing in favour of #222. Apologies I thought #222 was an isolated issue until you raised this.

Please see my comment on #222 and contribute on that issue to help solve this.
