### ISSUE TITLE
npm test not working after npm install

### ISSUE THREAD

**Issue by bengro** [lathonez/clicker#59]
When running after a fresh clone:
npm install
npm test

I got:
[16:31:38] Requiring external module ts-node/register
Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pivotal/workspace/clicker/test/gulpfile.ts:9:17)
    at Module._compile (module.js:409:26)
    at Object.loader (/Users/pivotal/workspace/clicker/node_modules/ts-node/src/ts-node.ts:225:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/Users/pivotal/workspace/clicker/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/pivotal/workspace/clicker/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/Users/pivotal/workspace/clicker/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/pivotal/workspace/clicker/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /Users/pivotal/workspace/clicker/node_modules/gulp/node_modules/liftoff/index.js:159:9
npm ERR! Test failed.  See above for more details.

Adding gulp-util to the dev dependencies fixed the issue.

**Comment by lathonez** [comment]
#60
