### ISSUE TITLE
Better stacktrace

### ISSUE THREAD

**Issue by mebibou** [lathonez/clicker#6]
I am using your code to implement the unit test in my project, but I have errors when running Karma and the stacktrace makes it impossible to debug what is actually going wrong. Example:
````
FAILED TESTS:
  MyApp
    ✖ initialises with one possible page
      PhantomJS 2.0.0 (Mac OS X 0.0.0)
    TypeError: undefined is not an object (evaluating 'provider.toString') (line 180)
    	at 
    	at 
    	at forEach ([native code])
    	at 
    	at 
    	at 
    	at 
    	at 
    	at /Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/test/karma/tests.config.js:41:18
    	at run (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:1217:29)
    	at zoneBoundFn (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:1194:29)
    	at lib$es6$promise$$internal$$tryCatch (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:442:25)
    	at lib$es6$promise$$internal$$invokeCallback (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:454:53)
    	at lib$es6$promise$$internal$$publish (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:425:53)
    	at /Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:97:12
    	at run (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:1217:29)
    	at zoneBoundFn (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:1194:29)
    	at lib$es6$promise$asap$$flush (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:236:18)
    TypeError: null is not an object (evaluating 'myApp.pages') (line 37)
    	at 
    	at /Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/test/karma/tests.config.js:41:18
    	at run (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:1217:29)
    	at zoneBoundFn (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:1194:29)
    	at lib$es6$promise$$internal$$tryCatch (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:442:25)
    	at lib$es6$promise$$internal$$invokeCallback (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:454:53)
    	at lib$es6$promise$$internal$$publish (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:425:53)
    	at /Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:97:12
    	at run (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:1217:29)
    	at zoneBoundFn (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:1194:29)
    	at lib$es6$promise$asap$$flush (/Users/groyer/Documents/workspace/helperchoice/helpizr-app-v2/node_modules/zone.js/dist/zone-microtask.js:236:18)
````

Is there any way to know in which file this `line 180` is located? or have the complete stacktrace with no empty lines? thanks

**Comment by lathonez** [comment]
Hey thanks for reaching out!

I haven't found a way of getting a better stack trace using PhatomJS2.

Here's the way I do it:

1. Change browser to "Chrome" here: https://github.com/lathonez/clicker/blob/master/test/karma.config.js#L94

1. Change singleRun to false here:  https://github.com/lathonez/clicker/blob/master/test/karma.config.js#L108

1. Rerun the test.

You should see Chrome pops up and runs through all the tests. As we've set singleRun to false, Karma should leave Chrome open at the end. On Chrome you should see Jasmine's home page, with a DEBUG button in the top right hand corner. If you click DEBUG, it'll open in a new tab and run through the tests again. F12 for dev tools and you should have a proper stack trace.

Incidentally I've switched to using Chrome full time personally (instead of PhantomJS2).

Let me know how go.

**Comment by mebibou** [comment]
Oh ok I see, this is what I usually do for my other angular projects.

However I think following your recommendations is not enough for the `singleRun`, because then nothing will happen when you change a source files because they need to be recompiled again to be picked up by karma. I've added a 'test.watch' gulp task to recompile the sources, but it kind of goes crazy when one file changes and re-run the tests multiple times, how have you done i?

**Comment by lathonez** [comment]
I only use single run = false for debugging. When I'm done debugging I kill
karma and run npm test again.

It isn't the best setup but I don't find myself having to resort to the
Jasmine debug all that often.

That being said I'd be obviously welcome a better setup.. Having a gulp
watch (with single run = false) is interesting, but I think it would need
to restart the karma server on change to be effective?

**Comment by mebibou** [comment]
Nope you don't have to restart the Karma, as you already set it up to watch the build files, so it could pick up the changes and rerun the tests. It works really well when you don't compile the sources, as it would just pick-up that one file changed and that's it, but because of the multiple compiled files when I tried it went on a loop. A simple example would be:
````
gulp.task('test.watch', function() {
  gulp.watch([
    config.paths.test.app,
    config.paths.test.spec,
    config.paths.test.typings
  ], ['test.compile']);
});

# change 'test' by
gulp.task('test', ['test.lint', 'test.compile', 'test.copyHTML', 'test.watch'], function() {
````

**Comment by lathonez** [comment]
@mebibou thanks a lot for this. I'd really appreciate it if you let me know if you find a better set up.

**Comment by DotHide** [comment]
That's great! @mebibou . Watch is better than single run. I've changed `gulpfile.ts` and it works.

```ts
// test/gulpfile.ts
...

// I added 2 functions
function watch(): any {
  'use strict';

  return gulp.watch(
    join(APP_DIR, '**/*.ts'), 
    ['test.compile', 'test.build.locker', 'test.build.typescript']
  );
}

function compile(done: any): any {
  runSequence(
    ['test.build.html', 'test.build.fonts', 'test.build.sass'],
    done
  );
}

// And then insert them into test task.
gulp.task('test', (done: any) => {
  runSequence(
    ['test.clean', 'test.lint'],
    ['test.compile', 'test.watch'],
    'test.build.locker',
    'test.build.typescript',
    'test.karma',
    done
  );
});
```

Then, when I use `npm test`, it will watch my `app/` folder and ts file. When I modify any app/**/*.ts, it will run test again automatically. That's it.

**Comment by lathonez** [comment]
@DotHide - nice!! I'm working on pulling some stuff in from [Angular 2 Seed][https://github.com/mgechev/angular2-seed] that should cover this.

**Comment by lathonez** [comment]
See also #19

**Comment by lathonez** [comment]
I've added watch and debug functionality similar to angular 2 seed: 5fcaaf4. Updated README with instructions.
