### ISSUE TITLE
While building i get error

### ISSUE THREAD

**Issue by yokeshvaradhan** [lathonez/clicker#67]
hi i tried your tutorial with a blank project with this link
http://lathonez.github.io/2016/ionic-2-e2e-testing/
all worked good but at the time of build i get error in my terminal winlow like this

Last login: Mon Apr  4 11:27:32 on ttys001
yokeshs-Mac-mini:myapp yokesh$ node_modules/gulp/bin/gulp.js --gulpfile test/gulpfile.ts --cwd ./ test.build
[11:35:58] Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
node_modules/angular2/src/facade/promise.d.ts (1,10): Cannot re-export name that is not defined in the module. (2661)
typings/browser/ambient/express/index.d.ts (18,27): Cannot find module 'express-serve-static-core'. (2307)
typings/browser/ambient/serve-static/index.d.ts (17,30): Cannot find module 'express-serve-static-core'. (2307)
    at getOutput (/Users/yokesh/myapp/node_modules/ts-node/src/ts-node.ts:209:13)
    at Object.loader (/Users/yokesh/myapp/node_modules/ts-node/src/ts-node.ts:224:23)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (/Users/yokesh/myapp/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/yokesh/myapp/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/yokesh/myapp/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/yokesh/myapp/node_modules/liftoff/index.js:185:9)
yokeshs-Mac-mini:myapp yokesh$ 

i could not get what wrong i have done, could u help me to sort out this issue

**Comment by nicopeeters** [comment]
Hi, I am getting the same output. Were you able to fix this?

**Comment by nicopeeters** [comment]
I fixed it by reinstalling the typings like you said in this issue: https://github.com/lathonez/clicker/issues/48 

`rm -rf typings
rm typings.json
wget https://raw.githubusercontent.com/lathonez/clicker/master/typings.json
typings install`

**Comment by lathonez** [comment]
@nicopeeters thank you.

@yokeshvaradhan did this solve your problem?

**Comment by yokeshvaradhan** [comment]
@lathonez No could u help me out by briefing the whole process step by step

**Comment by lathonez** [comment]
```
rm -rf typings
rm typings.json
wget https://raw.githubusercontent.com/lathonez/clicker/master/typings.json
typings install
```

**Comment by yokeshvaradhan** [comment]
@lathonez i am new to ionic  do i have to install protractor, my task is to clone a simple app and check its  header could u help me

**Comment by lathonez** [comment]
> clone a simple app and check its header

If that's all you want to do, follow the [Ionic 2 Tutorial](http://ionicframework.com/docs/v2/getting-started/tutorial/)
