### ISSUE TITLE
Unable to execute this command

### ISSUE THREAD

**Issue by yokeshvaradhan** [lathonez/clicker#72]
I done correctly all the above steps but when i execute this command in my terminal `node_modules/gulp/bin/gulp.js --gulpfile test/gulpfile.ts --cwd ./ test.build` it says that

```
okeshs-Mac-mini:Myapp yokesh$ node_modules/gulp/bin/gulp.js --gulpfile test/gulpfile.ts --cwd ./ test.build
[10:22:10] Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
typings/browser/ambient/express/index.d.ts (18,27): Cannot find module 'express-serve-static-core'. (2307)
    at getOutput (/Users/yokesh/Myapp/node_modules/ts-node/src/ts-node.ts:209:13)
    at Object.loader (/Users/yokesh/Myapp/node_modules/ts-node/src/ts-node.ts:224:23)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/Users/yokesh/Myapp/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/yokesh/Myapp/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/yokesh/Myapp/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/yokesh/Myapp/node_modules/gulp/node_modules/liftoff/index.js:185:9)
```

could someone help me

**Comment by lathonez** [comment]
Hey,

Thanks for reaching out.

Before we go any further, have you been able to clone down this repo and run the test suite against it?

e.g.

```
git clone https://github.com/lathonez/clicker.git
cd clicker
npm install       # or `npm run reinstall` if you get an error
npm test          # run unit tests
```

Thanks

**Comment by yokeshvaradhan** [comment]
ya i cloned it and i run it using ionic serve, could able to view all components

**Comment by lathonez** [comment]
And the tests are working for you also?

**Comment by yokeshvaradhan** [comment]
ya its working but i am trying to run it in an starter app at that time i am getting that err

**Comment by lathonez** [comment]
copy the package.json from this repo into your starter app and run npm install

**Comment by yokeshvaradhan** [comment]
stil i am getting the same

yokeshs-Mac-mini:Myapp yokesh$ node_modules/gulp/bin/gulp.js --gulpfile test/gulpfile.ts --cwd ./ test.build
[13:13:55] Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
typings/browser/ambient/express/index.d.ts (18,27): Cannot find module 'express-serve-static-core'. (2307)
    at getOutput (/Users/yokesh/Myapp/node_modules/ts-node/src/ts-node.ts:209:13)
    at Object.loader (/Users/yokesh/Myapp/node_modules/ts-node/src/ts-node.ts:224:23)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/Users/yokesh/Myapp/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/yokesh/Myapp/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/yokesh/Myapp/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/yokesh/Myapp/node_modules/gulp/node_modules/liftoff/index.js:185:9)
yokeshs-Mac-mini:Myapp yokesh$

**Comment by lathonez** [comment]
Can you commit what you have onto git and let me know where it is, I'll take a look.

**Comment by yokeshvaradhan** [comment]
https://bitbucket.org/yokeshvaradhan/ionic2-starter-e2e

**Comment by lathonez** [comment]
As part of this I've been upgrading my repo to the latest of everything.

Eventually I ran across your error. It is fixed with:

`typings install --ambient --save express-serve-static-core`

**Comment by lathonez** [comment]
I've also fixed the blog post to include that missing typing.

Thanks again for raising this.

**Comment by yokeshvaradhan** [comment]
another issue could u help me
i am in the last step 
yokeshs-Mac-mini:myApp yokesh$ sudo npm run e2e 
Password:

> @ e2e /Users/yokesh/myApp
> gulp --gulpfile test/gulpfile.ts --cwd ./ test.build && ./node_modules/protractor/bin/protractor test/protractor.conf.js

[13:00:02] Requiring external module ts-node/register
[13:00:10] sourced Ionic's gulpfile @ /Users/yokesh/myApp/gulpfile.js
[13:00:10] Using gulpfile ~/myApp/test/gulpfile.ts
[13:00:10] Starting 'test.build'...
[13:00:10] Starting 'test.clean'...
[13:00:10] Deleted /Users/yokesh/myApp/www/build/test
[13:00:10] Finished 'test.clean' after 27 ms
[13:00:10] Starting 'sass'...
[13:00:10] Starting 'fonts'...
[13:00:10] Starting 'html'...
[13:00:10] Finished 'html' after 78 ms
[13:00:10] Finished 'fonts' after 94 ms
[13:00:13] Finished 'sass' after 2.89 s
[13:00:13] Starting 'test.build.typescript'...
[13:00:18] Finished 'test.build.typescript' after 4.81 s
[13:00:18] Finished 'test.build' after 7.73 s
WARNING - pattern ../www/build/test/**/*.e2e.js did not match any files.
[launcher] Process exited with error code 1
/Users/yokesh/myApp/node_modules/protractor/node_modules/q/q.js:155
                throw e;
                ^

Error: Spec patterns did not match any files.
    at Runner.run (/Users/yokesh/myApp/node_modules/protractor/built/runner.js:286:11)
    at TaskRunner.run (/Users/yokesh/myApp/node_modules/protractor/built/taskRunner.js:109:27)
    at createNextTaskRunner (/Users/yokesh/myApp/node_modules/protractor/built/launcher.js:216:20)
    at /Users/yokesh/myApp/node_modules/protractor/built/launcher.js:239:7
    at _fulfilled (/Users/yokesh/myApp/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/yokesh/myApp/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/yokesh/myApp/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/yokesh/myApp/node_modules/protractor/node_modules/q/q.js:604:44
    at runSingle (/Users/yokesh/myApp/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/Users/yokesh/myApp/node_modules/protractor/node_modules/q/q.js:125:13)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "e2e"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! @ e2e: `gulp --gulpfile test/gulpfile.ts --cwd ./ test.build && ./node_modules/protractor/bin/protractor test/protractor.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ e2e script 'gulp --gulpfile test/gulpfile.ts --cwd ./ test.build && ./node_modules/protractor/bin/protractor test/protractor.conf.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --gulpfile test/gulpfile.ts --cwd ./ test.build && ./node_modules/protractor/bin/protractor test/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yokesh/myApp/npm-debug.log
yokeshs-Mac-mini:myApp yokesh$

**Comment by lathonez** [comment]
Please raise another issue.
