### ISSUE TITLE
clickerList.e2e.ts: Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .clickerList)

### ISSUE THREAD

**Issue by tja4472** [lathonez/clicker#84]
i'm a novice with Protactor but adding this to clickerList.e2e.ts seemed to work.

```javascript

let flow: any = protractor.promise.controlFlow();
function waitOne(): any {
  'use strict';
  return protractor.promise.delayed(1000);
}

function sleep(): void {
  'use strict';
  flow.execute(waitOne);
}

...

  it('should add a Clicker', () => {
    'test clicker one'.split('').forEach((c) => clickerField.sendKeys(c));
    clickerButton.click();
    sleep();
    //browser.pause();     
    expect(firstClicker.getText()).toEqual('test clicker one (0)');
  });
```

```Error
C:\VSCode\Ionic2\github\clicker>npm run e2e-win

> clicker@1.1.0 e2e-win C:\VSCode\Ionic2\github\clicker
> gulp --gulpfile test/gulpfile.ts --cwd ./ build-e2e && protractor test/protractor.conf.js

[14:57:29] Requiring external module ts-node/register
[14:57:34] sourced Ionic's gulpfile @ C:\VSCode\Ionic2\github\clicker\gulpfile.js
[14:57:34] Using gulpfile C:\VSCode\Ionic2\github\clicker\test\gulpfile.ts
[14:57:34] Starting 'build-e2e'...
[14:57:36] Finished 'build-e2e' after 1.43 s
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Spec started
Started

  ClickerApp
    ✓ should have a title
.    ✓ should have <nav>
.    ✓ should have correct nav text for Home
.    ✓ has a menu button that displays the left menu
.    ✓ the left menu has a link with title Clickers
.    ✓ the left menu has a link with title Goodbye Ionic
.
  ClickerList
    ✓ should switch into clickers page from menu
.    ✓ has an input box for new Clickers
.    ✓ should add a Clicker
.    ✗ should click a Clicker
      - Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .clickerList)
F    ✗ should delete a Clicker
      - Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .button-outline-danger)
F
  Page2
    ✓ should have correct text when Goodbye Ionic is selected
.
**************************************************
*                    Failures                    *
**************************************************

1) ClickerList should click a Clicker
  - Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .clickerList)

2) ClickerList should delete a Clicker
  - Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .button-outline-danger)

Executed 12 of 12 specs (2 FAILED) in 22 secs.


Failures:
1) ClickerList should click a Clicker
  Message:
    Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .clickerList)
  Stack:
    Error: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .clickerList)
        at C:\VSCode\Ionic2\github\clicker\node_modules\protractor\built\element.js:245:15
        at Promise.invokeCallback_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2773:21)
        at C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2652:27
        at C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:639:7
        at process._tickCallback (node.js:369:9)
    Error
        at [object Object].ElementArrayFinder.applyAction_ (C:\VSCode\Ionic2\github\clicker\node_modules\protractor\built\element.js:380:21)
        at [object Object].ElementArrayFinder.(anonymous function) [as click] (C:\VSCode\Ionic2\github\clicker\node_modules\protractor\built\element.js:78:17)
        at [object Object].ElementFinder.(anonymous function) [as click] (C:\VSCode\Ionic2\github\clicker\node_modules\protractor\built\element.js:708:7)
        at Object.<anonymous> (C:\VSCode\Ionic2\github\clicker\www\build\test\pages\clickerList\clickerList.e2e.js:36:22)
        at C:\VSCode\Ionic2\github\clicker\node_modules\jasminewd2\index.js:96:23
        at new Promise (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:1043:7)
        at controlFlowExecute (C:\VSCode\Ionic2\github\clicker\node_modules\jasminewd2\index.js:82:18)
        at TaskQueue.execute_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2773:21)
        at C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2697:25
    From: Task: Run it("should click a Clicker") in control flow
        at Object.<anonymous> (C:\VSCode\Ionic2\github\clicker\node_modules\jasminewd2\index.js:81:14)
        at C:\VSCode\Ionic2\github\clicker\node_modules\jasminewd2\index.js:18:5
        at Promise.invokeCallback_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2773:21)
        at C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2652:27
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\VSCode\Ionic2\github\clicker\www\build\test\pages\clickerList\clickerList.e2e.js:35:5)
        at Object.<anonymous> (C:\VSCode\Ionic2\github\clicker\www\build\test\pages\clickerList\clickerList.e2e.js:18:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)

2) ClickerList should delete a Clicker
  Message:
    Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .button-outline-danger)
  Stack:
    Error: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .button-outline-danger)
        at C:\VSCode\Ionic2\github\clicker\node_modules\protractor\built\element.js:245:15
        at Promise.invokeCallback_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2773:21)
        at C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2652:27
        at C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:639:7
        at process._tickCallback (node.js:369:9)
    Error
        at [object Object].ElementArrayFinder.applyAction_ (C:\VSCode\Ionic2\github\clicker\node_modules\protractor\built\element.js:380:21)
        at [object Object].ElementArrayFinder.(anonymous function) [as click] (C:\VSCode\Ionic2\github\clicker\node_modules\protractor\built\element.js:78:17)
        at [object Object].ElementFinder.(anonymous function) [as click] (C:\VSCode\Ionic2\github\clicker\node_modules\protractor\built\element.js:708:7)
        at Object.<anonymous> (C:\VSCode\Ionic2\github\clicker\www\build\test\pages\clickerList\clickerList.e2e.js:40:22)
        at C:\VSCode\Ionic2\github\clicker\node_modules\jasminewd2\index.js:96:23
        at new Promise (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:1043:7)
        at controlFlowExecute (C:\VSCode\Ionic2\github\clicker\node_modules\jasminewd2\index.js:82:18)
        at TaskQueue.execute_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2773:21)
        at C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2697:25
    From: Task: Run it("should delete a Clicker") in control flow
        at Object.<anonymous> (C:\VSCode\Ionic2\github\clicker\node_modules\jasminewd2\index.js:81:14)
        at C:\VSCode\Ionic2\github\clicker\node_modules\jasminewd2\index.js:18:5
        at Promise.invokeCallback_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2773:21)
        at C:\VSCode\Ionic2\github\clicker\node_modules\selenium-webdriver\lib\promise.js:2652:27
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\VSCode\Ionic2\github\clicker\www\build\test\pages\clickerList\clickerList.e2e.js:39:5)
        at Object.<anonymous> (C:\VSCode\Ionic2\github\clicker\www\build\test\pages\clickerList\clickerList.e2e.js:18:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)

12 specs, 2 failures
Finished in 22.366 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 failed 2 test(s)
[launcher] overall: 2 failed spec(s)
[launcher] Process exited with error code 1

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tim\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e-win"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! clicker@1.1.0 e2e-win: `gulp --gulpfile test/gulpfile.ts --cwd ./ build-e2e && protractor test/protractor.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clicker@1.1.0 e2e-win script 'gulp --gulpfile test/gulpfile.ts --cwd ./ build-e2e && protractor test/protractor.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the clicker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --gulpfile test/gulpfile.ts --cwd ./ build-e2e && protractor test/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs clicker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls clicker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\VSCode\Ionic2\github\clicker\npm-debug.log

C:\VSCode\Ionic2\github\clicker>
```

Regards
Tim

**Comment by lathonez** [comment]
Interesting. This doesn't happen for me or Travis.

Does this work?

```diff
   it('should add a Clicker', () => {
     'test clicker one'.split('').forEach((c) => clickerField.sendKeys(c));
-    clickerButton.click();
-    expect(firstClicker.getText()).toEqual('TEST CLICKER ONE (0)');
+    clickerButton.click()
+      .then(() => {
+        expect(firstClicker.getText()).toEqual('TEST CLICKER ONE (0)');
+      });
   });
 
   it('should click a Clicker', () => {
-    firstClicker.click();
-    expect(firstClicker.getText()).toEqual('TEST CLICKER ONE (1)');
+    firstClicker.click()
+      .then(() => {
+        expect(firstClicker.getText()).toEqual('TEST CLICKER ONE (1)');
+      });
   });
```

I'm keen to avoid sleeping if possible, though I have had to use it elsewhere.

**Comment by tja4472** [comment]
I'm afraid not. Same error.

```typescript
  it('should add a Clicker', () => {
    'test clicker one'.split('').forEach((c) => clickerField.sendKeys(c));
    // clickerButton.click();
    // expect(firstClicker.getText()).toEqual('TEST CLICKER ONE (0)');
    clickerButton.click()
      .then(() => {
        expect(firstClicker.getText()).toEqual('TEST CLICKER ONE (0)');
      });
    // sleep();
  });

  it('should click a Clicker', () => {
    // firstClicker.click();
    // expect(firstClicker.getText()).toEqual('TEST CLICKER ONE (1)');
    firstClicker.click()
      .then(() => {
        expect(firstClicker.getText()).toEqual('TEST CLICKER ONE (1)');
      });
  });
```

**Comment by lathonez** [comment]
Cheers, I'll put in the sleep you suggested.

**Comment by lathonez** [comment]
https://github.com/lathonez/clicker/commit/5d3e0014d6c94575757c192ee8ed48c57a835f94

Should be the same functionality?

**Comment by tja4472** [comment]
Worked fine.

Thanks
Tim

```
C:\VSCode\Ionic2\github\clicker>npm run e2e

> clicker@1.1.0 e2e C:\VSCode\Ionic2\github\clicker
> gulp --gulpfile test/gulpfile.ts --cwd ./ build-e2e && protractor test/protractor.conf.js

[09:44:10] Requiring external module ts-node/register
[09:44:15] sourced Ionic's gulpfile @ C:\VSCode\Ionic2\github\clicker\gulpfile.js
[09:44:15] Using gulpfile C:\VSCode\Ionic2\github\clicker\test\gulpfile.ts
[09:44:15] Starting 'build-e2e'...
[09:44:16] Finished 'build-e2e' after 1.46 s
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Spec started
Started

  ClickerApp
    ✓ should have a title
.    ✓ should have <nav>
.    ✓ should have correct nav text for Home
.    ✓ has a menu button that displays the left menu
.    ✓ the left menu has a link with title Clickers
.    ✓ the left menu has a link with title Goodbye Ionic
.
  ClickerList
    ✓ should switch into clickers page from menu
.    ✓ has an input box for new Clickers
.    ✓ should add a Clicker
.    ✓ should click a Clicker
.    ✓ should delete a Clicker
.
  Page2
    ✓ should have correct text when Goodbye Ionic is selected
.
Executed 12 of 12 specs SUCCESS in 23 secs.



12 specs, 0 failures
Finished in 23.344 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 passed
```

**Comment by lathonez** [comment]
Sweet thanks
