### ISSUE TITLE
ionic state restore fails

### ISSUE THREAD

**Issue by mchapman** [lathonez/clicker#88]
Just did a git clone and npm i.  Got as far as the post install and got 

```
> clicker@1.2.0 postinstall /home/mark/Projects/clicker
> ionic state restore && typings install && webdriver-manager update && cp test/karma-static/*.html node_modules/karma/static


Error: Cannot find module './project'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mark/.npm-global/lib/node_modules/ionic/lib/ionic/state.js:36:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)


Cannot find module './project' (CLI v2.0.0-beta.22)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.4.3

```

**Comment by lathonez** [comment]
Hmm it's working here and in CI.

Try upgrading your global ionic and cordova to latest? I'm on ionic@beta.24.

```
x220:~/code$ cordova --version
6.1.1
x220:~/code$ ionic --version
2.0.0-beta.24
```

**Comment by mchapman** [comment]
That worked, though I had to run `npm build` before `npm start` (contrary to what it says in the readme) otherwise there were missing files
GET http://localhost:8100/build/js/es6-shim.min.js 
GET http://localhost:8100/build/js/angular2-polyfills.js 
GET http://localhost:8100/build/js/app.bundle.js

Sorry it took so long to do (holiday weekend in the UK)

**Comment by lathonez** [comment]
You definitely shouldn't have to run any kind of build task before start.

All npm start does is call `ionic serve`:

```
x220:~/code/clicker$ rm -rf build
x220:~/code/clicker$ npm start

> clicker@1.2.0 start /home/lathonez/code/clicker
> ionic serve


Running 'serve:before' gulp task before serve
[09:14:17] Starting 'clean'...
[09:14:17] Finished 'clean' after 23 ms
[09:14:17] Starting 'watch'...
[09:14:17] Starting 'sass'...
[09:14:17] Starting 'html'...
[09:14:17] Starting 'fonts'...
[09:14:17] Starting 'scripts'...
[09:14:18] Finished 'scripts' after 38 ms
[09:14:18] Finished 'html' after 44 ms
[09:14:18] Finished 'fonts' after 59 ms
[09:14:18] Finished 'sass' after 911 ms
7 MB bytes written (8.21 seconds)
[09:14:30] Finished 'watch' after 13 s
[09:14:30] Starting 'serve:before'...
[09:14:30] Finished 'serve:before' after 6.37 μs

Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ 
```
