### ISSUE TITLE
Duplicate typing identifiers raised by @rozumny

### ISSUE THREAD

**Issue by lathonez** [lathonez/clicker#94]
I see your recent work on migration to the latest angular/ionic release. thank you so much for all your hard work :) 

Does the latest build works for you? when I run npm test I get 

```
...
typings/main/ambient/selenium-webdriver/index.d.ts (5386,5): Duplicate identifier 'export='. (2300)
typings/main/ambient/selenium-webdriver/index.d.ts (5390,5): Duplicate identifier 'export='. (2300)
typings/main/ambient/selenium-webdriver/index.d.ts (5394,5): Duplicate identifier 'export='. (2300)
    at getOutput (/Users/rozumny/Development/usu/clicker/node_modules/ts-node/src/ts-node.ts:210:13)
    at Object.loader (/Users/rozumny/Development/usu/clicker/node_modules/ts-node/src/ts-node.ts:225:23)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/Users/rozumny/Development/usu/clicker/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/rozumny/Development/usu/clicker/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/rozumny/Development/usu/clicker/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/rozumny/Development/usu/clicker/node_modules/liftoff/index.js:185:9)
npm ERR! Test failed.  See above for more details.
```

Not sure whether it’s happening, because of my local node/ionic versions or because the repo needs to be fixed.

**Comment by lathonez** [comment]
@rozumny

You can always see the latest build status on [travis](https://travis-ci.org/lathonez/clicker)

The latest upgrade included typings 1.0.4, which has some breaking changes to their JSON layout from a 0.* version.

I suggest:

`rm -rf node_modules platforms plugins typings && npm install`

If you're using the clicker repo directly this should work for you, let me know otherwise

**Comment by rozumny** [comment]
hello, today morning I finally managed to get it working. I had to use node 4.1.2. With node 4.4.4 it was not working. Maybe you could mention this in the readme.md. thank you.

**Comment by lathonez** [comment]
Any idea why it doesn't work on 4.4.4? I'm on 5.11.1 and travis indeed uses 4.1.2.

The specific platform requirements for this repository should be identical to angular2 and ionic 2. If this isn't the case we need to establish why.

**Comment by lathonez** [comment]
Closing..
