### ISSUE TITLE
Unit test does not run any unit test and gives gulp error

### ISSUE THREAD

**Issue by mbakker96** [lathonez/clicker#97]
Hello,

I followed the unit test tutorial of this repo but I've a error when I run npm test. 

When I run `npm test` It does not make a `www/build/test` folder.

Does someone know how to fix this?

```typescript
describe('A suite', () => {
    it('contains spec with an expectation', () => {
        expect(true).toBe(true);
    });
});
```

```bash
Mac-mini:app martijnbakker$ npm test

> app@ test /Users/martijnbakker/projects/mobile/app
> gulp --gulpfile test/gulpfile.ts --cwd ./ unit-test

[09:53:46] Requiring external module ts-node/register
[09:53:49] Using gulpfile ~/projects/mobile/app/test/gulpfile.ts
[09:53:49] Starting 'unit-test'...
[09:53:49] Starting 'lint'...
[09:53:49] Starting 'html'...
[09:53:51] Finished 'lint' after 1.92 s
[09:53:51] Finished 'html' after 1.9 s
[09:53:51] Starting 'karma'...

START:
25 05 2016 09:54:02.728:INFO [framework.browserify]: bundle built
25 05 2016 09:54:02.752:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
25 05 2016 09:54:02.755:INFO [launcher]: Starting browser PhantomJS
25 05 2016 09:54:03.257:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#YJiZv3tqgZk8lZaTAAAA with id 34817495
25 05 2016 09:54:33.260:WARN [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Disconnected (1 times), because no message in 30000 ms.

Finished in 30.005 secs / 0 secs

[09:54:33] 'karma' errored after 42 s
[09:54:33] Error: 1
    at formatError (/Users/martijnbakker/projects/mobile/app/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/martijnbakker/projects/mobile/app/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:95:20)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/martijnbakker/projects/mobile/app/node_modules/orchestrator/index.js:264:8)
    at /Users/martijnbakker/projects/mobile/app/node_modules/orchestrator/index.js:275:23
    at finish (/Users/martijnbakker/projects/mobile/app/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/martijnbakker/projects/mobile/app/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/martijnbakker/projects/mobile/app/node_modules/karma/lib/server.js:336:7)
    at Server.<anonymous> (/Users/martijnbakker/projects/mobile/app/node_modules/karma/lib/server.js:347:9)
    at Server.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Server.emit (events.js:179:7)
    at emitCloseNT (net.js:1541:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[09:54:33] 'unit-test' errored after 44 s
[09:54:33] Error in plugin 'run-sequence'
Message:
    An error occured in task 'karma'.
npm ERR! Test failed.  See above for more details.
```

**Comment by mbakker96** [comment]
`npm run karma` works only on the app.spec.ts and not in the unit test that are located in `pages/**/*ts`

**Comment by mbakker96** [comment]
I fixet it when I deleted main() function out of my unit test

**Comment by kwv** [comment]
atom-beautify was _helpfully_ padding  `%MAPPINGS%` with spaces in `test/karma-static/context.html` and `test/karma-static/debug.html` to look like `% MAPPINGS %`

Karma would choke, and the result was the same Error 1 message.

**Comment by lathonez** [comment]
huh.

Thoes files shouldn't be used after the initial npm install which [copies them into node_modules](https://github.com/lathonez/clicker/blob/master/package.json#L67).

I guess `atom-beautify` was doing padding before this happened.

I don't use atom myself. Is there some config I can add to the project to prevent this from happening for other users?

**Comment by kwv** [comment]
Its not a fault of project, but rather poor workflow on my part.  After pulling clicker, I copied the files `test/karma-static/*.html` into my Ionic project using atom.
